# -*- coding: utf-8 -*-
"""PrezzoBenzinaGiornoSettimana

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FWudK9HCEaf8K-pAHIOLddDtxJiEs4Nf
"""

import pandas as pd

import seaborn as sns

import datetime
#from datetime import datetime
#import datetime as dt

"""https://www.mise.gov.it/index.php/it/open-data/elenco-dataset/carburanti-prezzi-praticati-e-anagrafica-degli-impianti"""

from google.colab import drive 
drive.mount('/content/gdrive')

prezzoBenzina = pd.read_csv('gdrive/My Drive/DataAnalysis/PrezzoBenzina/prezzo_alle_8.csv',delimiter=';',skiprows=1)

prezzoBenzina

impianti = pd.read_csv('gdrive/My Drive/DataAnalysis/PrezzoBenzina/anagrafica_impianti_attivi.csv', on_bad_lines='skip',delimiter=';',skiprows=1)

impianti

df = pd.merge(prezzoBenzina, impianti, how='left', on ='idImpianto')
df

df.dtypes

df['dtComu']= pd.to_datetime(df['dtComu'])
df

df['dtComu'] = pd.to_datetime(df['dtComu'].dt.strftime('%d/%m/%y'))
df

prova=df.groupby(['Bandiera', 'dtComu'])["prezzo"].mean()
prova

df2=impianti.groupby(['Bandiera'],as_index=False)['Indirizzo'].count()
df2

df2 = df2[df2.Indirizzo >= 1000]
df2

df_best=df[df['Bandiera'].isin(df2['Bandiera'])]
df_best

df_best.dtypes

df_best_medio=df_best.groupby(['Bandiera','dtComu'],as_index=False)['prezzo'].mean()
df_best_medio

sns.relplot(data=df_best_medio,x='dtComu',y='prezzo',hue='Bandiera',height=6, aspect=3,kind='line')

df_best.groupby(['Bandiera'],as_index=False)['prezzo'].mean()

df_best_mean=df_best.groupby('Bandiera',as_index=False)['prezzo'].mean()
df_best_mean.sort_values(['prezzo'])

df_best['day_of_week'] = df_best['dtComu'].apply(lambda x: datetime.datetime.strftime(x, '%A'))
df_best

df_best_week=df_best.groupby(['Bandiera','day_of_week'],as_index=False)['prezzo'].mean()
df_best_week['day_of_week'] = pd.Categorical(df_best_week['day_of_week'],categories=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday","Sunday"],ordered=True)
df_best_week = df_best_week.sort_values('day_of_week',ascending=False)
df_best_week

sns.relplot(data=df_best_week,x='day_of_week',y='prezzo',hue='Bandiera',kind='line',height=6, aspect=3)

df_best_week_prova=df_best_week.groupby('day_of_week',as_index=False)['prezzo'].mean()
df_best_week_prova.sort_values(['prezzo'])